import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:splittymate/models/currency.dart';

final currenciesProvider = Provider((ref) => _currencies);
final defaultAppCurrency = _currencies['USD']!;

const _currencies = {
  'AED':
      Currency(name: 'United Arab Emirates Dirham', symbol: 'د.إ', code: 'AED'),
  'AFN': Currency(name: 'Afghan Afghani', symbol: '؋', code: 'AFN'),
  'ALL': Currency(name: 'Albanian Lek', symbol: 'L', code: 'ALL'),
  'AMD': Currency(name: 'Armenian Dram', symbol: '֏', code: 'AMD'),
  'AOA': Currency(name: 'Angolan Kwanza', symbol: 'Kz', code: 'AOA'),
  'ARS': Currency(name: 'Argentine Peso', symbol: '\$', code: 'ARS'),
  'AUD': Currency(name: 'Australian Dollar', symbol: '\$', code: 'AUD'),
  'AWG': Currency(name: 'Aruban Florin', symbol: 'ƒ', code: 'AWG'),
  'AZN': Currency(name: 'Azerbaijani Manat', symbol: '₼', code: 'AZN'),
  'BAM': Currency(
      name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', code: 'BAM'),
  'BBD': Currency(name: 'Barbadian Dollar', symbol: '\$', code: 'BBD'),
  'BDT': Currency(name: 'Bangladeshi Taka', symbol: '৳', code: 'BDT'),
  'BGN': Currency(name: 'Bulgarian Lev', symbol: 'лв', code: 'BGN'),
  'BHD': Currency(name: 'Bahraini Dinar', symbol: 'BD', code: 'BHD'),
  'BMD': Currency(name: 'Bermudan Dollar', symbol: '\$', code: 'BMD'),
  'BND': Currency(name: 'Brunei Dollar', symbol: '\$', code: 'BND'),
  'BOB': Currency(name: 'Bolivian Boliviano', symbol: 'Bs.', code: 'BOB'),
  'BRL': Currency(name: 'Brazilian Real', symbol: 'R\$', code: 'BRL'),
  'BSD': Currency(name: 'Bahamian Dollar', symbol: '\$', code: 'BSD'),
  'BTN': Currency(name: 'Bhutanese Ngultrum', symbol: 'Nu.', code: 'BTN'),
  'BWP': Currency(name: 'Botswanan Pula', symbol: 'P', code: 'BWP'),
  'BYN': Currency(name: 'Belarusian Ruble', symbol: 'Br', code: 'BYN'),
  'BZD': Currency(name: 'Belize Dollar', symbol: 'BZ\$', code: 'BZD'),
  'CAD': Currency(name: 'Canadian Dollar', symbol: '\$', code: 'CAD'),
  'CDF': Currency(name: 'Congolese Franc', symbol: 'FC', code: 'CDF'),
  'CHF': Currency(name: 'Swiss Franc', symbol: 'CHF', code: 'CHF'),
  'CLP': Currency(name: 'Chilean Peso', symbol: '\$', code: 'CLP'),
  'CNY': Currency(name: 'Chinese Yuan', symbol: '¥', code: 'CNY'),
  'COP': Currency(name: 'Colombian Peso', symbol: 'Col\$', code: 'COP'),
  'CRC': Currency(name: 'Costa Rican Colón', symbol: '₡', code: 'CRC'),
  'CUC': Currency(name: 'Cuban Convertible Peso', symbol: '\$', code: 'CUC'),
  'CUP': Currency(name: 'Cuban Peso', symbol: '\$', code: 'CUP'),
  'CVE': Currency(name: 'Cape Verdean Escudo', symbol: 'Esc', code: 'CVE'),
  'CZK': Currency(name: 'Czech Koruna', symbol: 'Kč', code: 'CZK'),
  'DJF': Currency(name: 'Djiboutian Franc', symbol: 'Fdj', code: 'DJF'),
  'DKK': Currency(name: 'Danish Krone', symbol: 'kr', code: 'DKK'),
  'DOP': Currency(name: 'Dominican Peso', symbol: 'RD\$', code: 'DOP'),
  'DZD': Currency(name: 'Algerian Dinar', symbol: 'د.ج', code: 'DZD'),
  'EGP': Currency(name: 'Egyptian Pound', symbol: '£', code: 'EGP'),
  'ERN': Currency(name: 'Eritrean Nakfa', symbol: 'Nfk', code: 'ERN'),
  'ETB': Currency(name: 'Ethiopian Birr', symbol: 'Br', code: 'ETB'),
  'EUR': Currency(name: 'Euro', symbol: '€', code: 'EUR'),
  'FJD': Currency(name: 'Fijian Dollar', symbol: '\$', code: 'FJD'),
  'FKP': Currency(name: 'Falkland Islands Pound', symbol: '£', code: 'FKP'),
  'GBP': Currency(name: 'British Pound', symbol: '£', code: 'GBP'),
  'GEL': Currency(name: 'Georgian Lari', symbol: '₾', code: 'GEL'),
  'GHS': Currency(name: 'Ghanaian Cedi', symbol: 'GH₵', code: 'GHS'),
  'GIP': Currency(name: 'Gibraltar Pound', symbol: '£', code: 'GIP'),
  'GMD': Currency(name: 'Gambian Dalasi', symbol: 'D', code: 'GMD'),
  'GNF': Currency(name: 'Guinean Franc', symbol: 'FG', code: 'GNF'),
  'GTQ': Currency(name: 'Guatemalan Quetzal', symbol: 'Q', code: 'GTQ'),
  'GYD': Currency(name: 'Guyanaese Dollar', symbol: '\$', code: 'GYD'),
  'HKD': Currency(name: 'Hong Kong Dollar', symbol: '\$', code: 'HKD'),
  'HNL': Currency(name: 'Honduran Lempira', symbol: 'L', code: 'HNL'),
  'HRK': Currency(name: 'Croatian Kuna', symbol: 'kn', code: 'HRK'),
  'HTG': Currency(name: 'Haitian Gourde', symbol: 'G', code: 'HTG'),
  'HUF': Currency(name: 'Hungarian Forint', symbol: 'Ft', code: 'HUF'),
  'IDR': Currency(name: 'Indonesian Rupiah', symbol: 'Rp', code: 'IDR'),
  'ILS': Currency(name: 'Israeli Shekel', symbol: '₪', code: 'ILS'),
  'INR': Currency(name: 'Indian Rupee', symbol: '₹', code: 'INR'),
  'IQD': Currency(name: 'Iraqi Dinar', symbol: 'ع.د', code: 'IQD'),
  'IRR': Currency(name: 'Iranian Rial', symbol: '﷼', code: 'IRR'),
  'ISK': Currency(name: 'Icelandic Króna', symbol: 'kr', code: 'ISK'),
  'JMD': Currency(name: 'Jamaican Dollar', symbol: 'J\$', code: 'JMD'),
  'JOD': Currency(name: 'Jordanian Dinar', symbol: 'JD', code: 'JOD'),
  'JPY': Currency(name: 'Japanese Yen', symbol: '¥', code: 'JPY'),
  'KES': Currency(name: 'Kenyan Shilling', symbol: 'KSh', code: 'KES'),
  'KGS': Currency(name: 'Kyrgystani Som', symbol: 'с', code: 'KGS'),
  'KHR': Currency(name: 'Cambodian Riel', symbol: '៛', code: 'KHR'),
  'KMF': Currency(name: 'Comorian Franc', symbol: 'CF', code: 'KMF'),
  'KPW': Currency(name: 'North Korean Won', symbol: '₩', code: 'KPW'),
  'KRW': Currency(name: 'South Korean Won', symbol: '₩', code: 'KRW'),
  'KWD': Currency(name: 'Kuwaiti Dinar', symbol: 'KD', code: 'KWD'),
  'KZT': Currency(name: 'Kazakhstani Tenge', symbol: '₸', code: 'KZT'),
  'LAK': Currency(name: 'Laotian Kip', symbol: '₭', code: 'LAK'),
  'LBP': Currency(name: 'Lebanese Pound', symbol: 'ل.ل', code: 'LBP'),
  'LKR': Currency(name: 'Sri Lankan Rupee', symbol: '₨', code: 'LKR'),
  'LRD': Currency(name: 'Liberian Dollar', symbol: '\$', code: 'LRD'),
  'LSL': Currency(name: 'Lesotho Loti', symbol: 'L', code: 'LSL'),
  'LYD': Currency(name: 'Libyan Dinar', symbol: 'ل.د', code: 'LYD'),
  'MAD': Currency(name: 'Moroccan Dirham', symbol: 'د.م.', code: 'MAD'),
  'MGA': Currency(name: 'Malagasy Ariary', symbol: 'Ar', code: 'MGA'),
  'MKD': Currency(name: 'Macedonian Denar', symbol: 'ден', code: 'MKD'),
  'MMK': Currency(name: 'Myanmar Kyat', symbol: 'K', code: 'MMK'),
  'MNT': Currency(name: 'Mongolian Tugrik', symbol: '₮', code: 'MNT'),
  'MOP': Currency(name: 'Macanese Pataca', symbol: 'P', code: 'MOP'),
  'MRO': Currency(name: 'Mauritanian Ouguiya', symbol: 'UM', code: 'MRO'),
  'MUR': Currency(name: 'Mauritian Rupee', symbol: '₨', code: 'MUR'),
  'MVR': Currency(name: 'Maldivian Rufiyaa', symbol: 'Rf', code: 'MVR'),
  'MWK': Currency(name: 'Malawian Kwacha', symbol: 'MK', code: 'MWK'),
  'MXN': Currency(name: 'Mexican Peso', symbol: '\$', code: 'MXN'),
  'MYR': Currency(name: 'Malaysian Ringgit', symbol: 'RM', code: 'MYR'),
  'MZN': Currency(name: 'Mozambican Metical', symbol: 'MT', code: 'MZN'),
  'NAD': Currency(name: 'Namibian Dollar', symbol: 'N\$', code: 'NAD'),
  'NGN': Currency(name: 'Nigerian Naira', symbol: '₦', code: 'NGN'),
  'NIO': Currency(name: 'Nicaraguan Córdoba', symbol: 'C\$', code: 'NIO'),
  'NOK': Currency(name: 'Norwegian Krone', symbol: 'kr', code: 'NOK'),
  'NPR': Currency(name: 'Nepalese Rupee', symbol: '₨', code: 'NPR'),
  'NZD': Currency(name: 'New Zealand Dollar', symbol: '\$', code: 'NZD'),
  'OMR': Currency(name: 'Omani Rial', symbol: 'ر.ع.', code: 'OMR'),
  'PAB': Currency(name: 'Panamanian Balboa', symbol: 'B/.', code: 'PAB'),
  'PEN': Currency(name: 'Peruvian Sol', symbol: 'S/.', code: 'PEN'),
  'PGK': Currency(name: 'Papua New Guinean Kina', symbol: 'K', code: 'PGK'),
  'PHP': Currency(name: 'Philippine Peso', symbol: '₱', code: 'PHP'),
  'PKR': Currency(name: 'Pakistani Rupee', symbol: '₨', code: 'PKR'),
  'PLN': Currency(name: 'Polish Złoty', symbol: 'zł', code: 'PLN'),
  'PYG': Currency(name: 'Paraguayan Guarani', symbol: '₲', code: 'PYG'),
  'QAR': Currency(name: 'Qatari Riyal', symbol: 'ر.ق', code: 'QAR'),
  'RON': Currency(name: 'Romanian Leu', symbol: 'lei', code: 'RON'),
  'RSD': Currency(name: 'Serbian Dinar', symbol: 'дин', code: 'RSD'),
  'RUB': Currency(name: 'Russian Ruble', symbol: '₽', code: 'RUB'),
  'RWF': Currency(name: 'Rwandan Franc', symbol: 'FRw', code: 'RWF'),
  'SAR': Currency(name: 'Saudi Riyal', symbol: '﷼', code: 'SAR'),
  'SCR': Currency(name: 'Seychellois Rupee', symbol: '₨', code: 'SCR'),
  'SDG': Currency(name: 'Sudanese Pound', symbol: 'ج.س.', code: 'SDG'),
  'SEK': Currency(name: 'Swedish Krona', symbol: 'kr', code: 'SEK'),
  'SGD': Currency(name: 'Singapore Dollar', symbol: '\$', code: 'SGD'),
  'SHP': Currency(name: 'Saint Helena Pound', symbol: '£', code: 'SHP'),
  'SLL': Currency(name: 'Sierra Leonean Leone', symbol: 'Le', code: 'SLL'),
  'SOS': Currency(name: 'Somali Shilling', symbol: 'Sh', code: 'SOS'),
  'SRD': Currency(name: 'Surinamese Dollar', symbol: '\$', code: 'SRD'),
  'STD':
      Currency(name: 'São Tomé and Príncipe Dobra', symbol: 'Db', code: 'STD'),
  'SYP': Currency(name: 'Syrian Pound', symbol: 'ل.س', code: 'SYP'),
  'SZL': Currency(name: 'Swazi Lilangeni', symbol: 'L', code: 'SZL'),
  'THB': Currency(name: 'Thai Baht', symbol: '฿', code: 'THB'),
  'TJS': Currency(name: 'Tajikistani Somoni', symbol: 'SM', code: 'TJS'),
  'TMT': Currency(name: 'Turkmenistan Manat', symbol: 'm', code: 'TMT'),
  'TND': Currency(name: 'Tunisian Dinar', symbol: 'د.ت', code: 'TND'),
  'TOP': Currency(name: 'Tongan Paʻanga', symbol: 'T\$', code: 'TOP'),
  'TRY': Currency(name: 'Turkish Lira', symbol: '₺', code: 'TRY'),
  'TTD':
      Currency(name: 'Trinidad and Tobago Dollar', symbol: 'TT\$', code: 'TTD'),
  'TVD': Currency(name: 'Tuvaluan Dollar', symbol: '\$', code: 'TVD'),
  'TWD': Currency(name: 'New Taiwan Dollar', symbol: 'NT\$', code: 'TWD'),
  'TZS': Currency(name: 'Tanzanian Shilling', symbol: 'TSh', code: 'TZS'),
  'UAH': Currency(name: 'Ukrainian Hryvnia', symbol: '₴', code: 'UAH'),
  'UGX': Currency(name: 'Ugandan Shilling', symbol: 'USh', code: 'UGX'),
  'USD': Currency(name: 'United States Dollar', symbol: '\$', code: 'USD'),
  'UYU': Currency(name: 'Uruguayan Peso', symbol: '\$', code: 'UYU'),
  'UZS': Currency(name: 'Uzbekistani Som', symbol: 'лв', code: 'UZS'),
  'VEF': Currency(name: 'Venezuelan Bolívar', symbol: 'Bs', code: 'VEF'),
  'VND': Currency(name: 'Vietnamese Đồng', symbol: '₫', code: 'VND'),
  'VUV': Currency(name: 'Vanuatu Vatu', symbol: 'VT', code: 'VUV'),
  'WST': Currency(name: 'Samoan Tala', symbol: 'T', code: 'WST'),
  'XAF':
      Currency(name: 'Central African CFA Franc', symbol: 'FCFA', code: 'XAF'),
  'XCD': Currency(name: 'East Caribbean Dollar', symbol: '\$', code: 'XCD'),
  'XDR': Currency(name: 'Special Drawing Rights', symbol: 'SDR', code: 'XDR'),
  'XOF': Currency(name: 'West African CFA Franc', symbol: 'CFA', code: 'XOF'),
  'XPF': Currency(name: 'CFP Franc', symbol: '₣', code: 'XPF'),
  'YER': Currency(name: 'Yemeni Rial', symbol: '﷼', code: 'YER'),
  'ZAR': Currency(name: 'South African Rand', symbol: 'R', code: 'ZAR'),
  'ZMW': Currency(name: 'Zambian Kwacha', symbol: 'ZK', code: 'ZMW'),
  'ZWL': Currency(name: 'Zimbabwean Dollar', symbol: 'Z\$', code: 'ZWL'),
};
