# .github/workflows/build.yml
name: Build Flutter APK

on:
  push:
    branches: [ signing-config ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Decode .env, key.properties and upload key file
      run: |
        echo "${{ secrets.ENV_BASE64 }}" | base64 -d > ${{ github.workspace }}/.env
        echo "${{ secrets.KEY_FILE_BASE64 }}" | base64 -d > ${{ github.workspace }}/android/splittymate-key.json
        echo "${{ secrets.KEY_PROPERTIES }}" > ${{ github.workspace }}/android/key.properties

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
        flutter-version-file: pubspec.yaml
        cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
        cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
        pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
        pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path

    - name: Install dependencies
      run: flutter pub get

    - name: Build APP Bundle
      run: flutter build appbundle --release

    - name: Upload AAB as artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab

    - name: Create fastlane service account key file
      run: |
        echo "${{ secrets.FASTLANE_SERVICE_ACCOUNT_KEY_JSON }}" > ${{ github.workspace }}/android/fastlane/splittymate-serviceaccount-fastlane-key.json

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        working-directory: 'android'

    - name: Upload to Google Play
      uses: maierj/fastlane-action@v3.1.0
      with:
        lane: 'internal'
        subdirectory: 'android'
